// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: v1alpha1/client/pb/affiliate.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Affiliate protobuf spec, as seen internally in the client code.
//
// Discovery service recieves Affiliate marshaled to protobuf and encrypted.
type Affiliate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// IPs are encoded using binary marshaling.
	Addresses       [][]byte      `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hostname        string        `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Nodename        string        `protobuf:"bytes,4,opt,name=nodename,proto3" json:"nodename,omitempty"`
	MachineType     string        `protobuf:"bytes,5,opt,name=machine_type,json=machineType,proto3" json:"machine_type,omitempty"`
	OperatingSystem string        `protobuf:"bytes,6,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Kubespan        *KubeSpan     `protobuf:"bytes,7,opt,name=kubespan,proto3,oneof" json:"kubespan,omitempty"`
	ControlPlane    *ControlPlane `protobuf:"bytes,8,opt,name=control_plane,json=controlPlane,proto3,oneof" json:"control_plane,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Affiliate) Reset() {
	*x = Affiliate{}
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affiliate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affiliate) ProtoMessage() {}

func (x *Affiliate) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affiliate.ProtoReflect.Descriptor instead.
func (*Affiliate) Descriptor() ([]byte, []int) {
	return file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP(), []int{0}
}

func (x *Affiliate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Affiliate) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Affiliate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Affiliate) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *Affiliate) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

func (x *Affiliate) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Affiliate) GetKubespan() *KubeSpan {
	if x != nil {
		return x.Kubespan
	}
	return nil
}

func (x *Affiliate) GetControlPlane() *ControlPlane {
	if x != nil {
		return x.ControlPlane
	}
	return nil
}

// KubeSpan optional configuration.
type KubeSpan struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address             []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AdditionalAddresses []*IPPrefix            `protobuf:"bytes,3,rep,name=additional_addresses,json=additionalAddresses,proto3" json:"additional_addresses,omitempty"`
	// Advertised filter is a list of filter expressions ("(!?)<cidr>") applied
	// to the additional_addresses and addresses.
	// If the expression starts with "!", the corresponding address is excluded.
	// Only addresses passing the filter are advertised to other peers.
	AdvertisedFilter []string `protobuf:"bytes,4,rep,name=advertised_filter,json=advertisedFilter,proto3" json:"advertised_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KubeSpan) Reset() {
	*x = KubeSpan{}
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeSpan) ProtoMessage() {}

func (x *KubeSpan) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeSpan.ProtoReflect.Descriptor instead.
func (*KubeSpan) Descriptor() ([]byte, []int) {
	return file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP(), []int{1}
}

func (x *KubeSpan) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KubeSpan) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *KubeSpan) GetAdditionalAddresses() []*IPPrefix {
	if x != nil {
		return x.AdditionalAddresses
	}
	return nil
}

func (x *KubeSpan) GetAdvertisedFilter() []string {
	if x != nil {
		return x.AdvertisedFilter
	}
	return nil
}

// IPPrefix contains CIDR.
type IPPrefix struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPs are encoded using binary marshaling.
	Ip            []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Bits          uint32 `protobuf:"varint,2,opt,name=bits,proto3" json:"bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPrefix) Reset() {
	*x = IPPrefix{}
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPrefix) ProtoMessage() {}

func (x *IPPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPrefix.ProtoReflect.Descriptor instead.
func (*IPPrefix) Descriptor() ([]byte, []int) {
	return file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP(), []int{2}
}

func (x *IPPrefix) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *IPPrefix) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

// Endpoint for the Affiliate KubeSpan spec as seen internally in the client code.
//
// Discovery service receives Affiliate marshaled to protobuf and encrypted.
type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPs are encoded using binary marshaling.
	Ip            []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ControlPlane optional configuration.
type ControlPlane struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiServerPort uint32                 `protobuf:"varint,1,opt,name=api_server_port,json=apiServerPort,proto3" json:"api_server_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlane) Reset() {
	*x = ControlPlane{}
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlane) ProtoMessage() {}

func (x *ControlPlane) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_client_pb_affiliate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlane.ProtoReflect.Descriptor instead.
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP(), []int{4}
}

func (x *ControlPlane) GetApiServerPort() uint32 {
	if x != nil {
		return x.ApiServerPort
	}
	return 0
}

var File_v1alpha1_client_pb_affiliate_proto protoreflect.FileDescriptor

const file_v1alpha1_client_pb_affiliate_proto_rawDesc = "" +
	"\n" +
	"\"v1alpha1/client/pb/affiliate.proto\x12\x17sidero.discovery.client\"\xfc\x02\n" +
	"\tAffiliate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\fR\taddresses\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\bnodename\x18\x04 \x01(\tR\bnodename\x12!\n" +
	"\fmachine_type\x18\x05 \x01(\tR\vmachineType\x12)\n" +
	"\x10operating_system\x18\x06 \x01(\tR\x0foperatingSystem\x12B\n" +
	"\bkubespan\x18\a \x01(\v2!.sidero.discovery.client.KubeSpanH\x00R\bkubespan\x88\x01\x01\x12O\n" +
	"\rcontrol_plane\x18\b \x01(\v2%.sidero.discovery.client.ControlPlaneH\x01R\fcontrolPlane\x88\x01\x01B\v\n" +
	"\t_kubespanB\x10\n" +
	"\x0e_control_plane\"\xc6\x01\n" +
	"\bKubeSpan\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12T\n" +
	"\x14additional_addresses\x18\x03 \x03(\v2!.sidero.discovery.client.IPPrefixR\x13additionalAddresses\x12+\n" +
	"\x11advertised_filter\x18\x04 \x03(\tR\x10advertisedFilter\".\n" +
	"\bIPPrefix\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04bits\x18\x02 \x01(\rR\x04bits\".\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"6\n" +
	"\fControlPlane\x12&\n" +
	"\x0fapi_server_port\x18\x01 \x01(\rR\rapiServerPortB<Z:github.com/siderolabs/discovery-api/api/v1alpha1/client/pbb\x06proto3"

var (
	file_v1alpha1_client_pb_affiliate_proto_rawDescOnce sync.Once
	file_v1alpha1_client_pb_affiliate_proto_rawDescData []byte
)

func file_v1alpha1_client_pb_affiliate_proto_rawDescGZIP() []byte {
	file_v1alpha1_client_pb_affiliate_proto_rawDescOnce.Do(func() {
		file_v1alpha1_client_pb_affiliate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_client_pb_affiliate_proto_rawDesc), len(file_v1alpha1_client_pb_affiliate_proto_rawDesc)))
	})
	return file_v1alpha1_client_pb_affiliate_proto_rawDescData
}

var file_v1alpha1_client_pb_affiliate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1alpha1_client_pb_affiliate_proto_goTypes = []any{
	(*Affiliate)(nil),    // 0: sidero.discovery.client.Affiliate
	(*KubeSpan)(nil),     // 1: sidero.discovery.client.KubeSpan
	(*IPPrefix)(nil),     // 2: sidero.discovery.client.IPPrefix
	(*Endpoint)(nil),     // 3: sidero.discovery.client.Endpoint
	(*ControlPlane)(nil), // 4: sidero.discovery.client.ControlPlane
}
var file_v1alpha1_client_pb_affiliate_proto_depIdxs = []int32{
	1, // 0: sidero.discovery.client.Affiliate.kubespan:type_name -> sidero.discovery.client.KubeSpan
	4, // 1: sidero.discovery.client.Affiliate.control_plane:type_name -> sidero.discovery.client.ControlPlane
	2, // 2: sidero.discovery.client.KubeSpan.additional_addresses:type_name -> sidero.discovery.client.IPPrefix
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1alpha1_client_pb_affiliate_proto_init() }
func file_v1alpha1_client_pb_affiliate_proto_init() {
	if File_v1alpha1_client_pb_affiliate_proto != nil {
		return
	}
	file_v1alpha1_client_pb_affiliate_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_client_pb_affiliate_proto_rawDesc), len(file_v1alpha1_client_pb_affiliate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_client_pb_affiliate_proto_goTypes,
		DependencyIndexes: file_v1alpha1_client_pb_affiliate_proto_depIdxs,
		MessageInfos:      file_v1alpha1_client_pb_affiliate_proto_msgTypes,
	}.Build()
	File_v1alpha1_client_pb_affiliate_proto = out.File
	file_v1alpha1_client_pb_affiliate_proto_goTypes = nil
	file_v1alpha1_client_pb_affiliate_proto_depIdxs = nil
}
